services:
  node-client:
    build: .
    container_name: abdl-bot
    network_mode: "container:gluetun" # All outgoing traffic goes through VPN
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # This "Anonymous Volume" protects node_modules
    restart: always
