import tracery from "tracery-grammar";
export const grammar = tracery.createGrammar({
  pet_name: [
    "sweetie",
    "sweetheart",
    "honey",
    "darling",
    "love",
    "cutie",
    "sweetie pie",
    "sweetness",
    "baby",
    "dear",
    "angel",
    "precious",
    "pumpkin",
  ],
  observation: [
    "this little #pet_name#",
    "somebody",
    "someone",
    "our little #pet_name#",
    "this #pet_name#",
    "a certain little #pet_name#",
  ],
  mess_observation: [
    "someone made a mess",
    "somebody had an accident",
    "this little one left a present",
    "somebody's been busy",
    "someone filled their pants",
    "this one made quite a mess",
    "looks like someone couldn't hold it",
    "somebody didn't make it to the potty",
  ],
  mess_ending: [
    "",
    " hmm?",
    " is that right?",
    " isn't that cozy?",
    " what a messy baby~",
    " and they seem so proud~",
    " what a good little mess-maker~",
    " and they're not even sorry~",
  ],
  enjoyment_verb: [
    "likes",
    "loves",
    "enjoys",
    "prefers",
    "needs",
    "wants",
    "is into",
    "is all about",
    "seems to like",
    "really likes",
    "actually likes",
  ],
  mess_descriptor: [
    "messy",
    "dirty",
    "soiled",
    "stinky",
    "loaded",
    "full",
    "heavy",
    "poopy",
    "stuffed",
    "overflowing",
    "sticky",
    "mushy",
    "warm and heavy",
    "nice and full",
    "absolutely loaded",
  ],
  wetness_descriptor: [
    "soggy",
    "wet",
    "soaked",
    "drenched",
    "squishy",
    "warm and wet",
    "nice and wet",
    "all wet",
    "good and soggy",
  ],
  diaper_noun: ["diaper", "nappy", "bottom", "padding", "tush"],
  taunt_ending: [
    ", don't you?",
    ", hmm?",
    ", is that right?",
    ", aren't you?",
    "",
    "~",
    "...",
    ", are we?",
    ", no?",
    ", huh?",
    ", you know?",
    ", am I right?",
    ", don't you think?",
    ", isn't that right?",
    "~ don't you agree?",
    ", or am I wrong?",
    ", right?",
    ", okay?",
    ", alright?",
    ", yeah?",
    ", see?",
    ", you feel that?",
    ", eh?",
  ],
  unsure_opener: ["", "you know,", "hey,", "um,", "well,", "so,"],
  bold_opener: [
    "Oh my~",
    "Aww~",
    "Well well~",
    "My my~",
    "Ooh~",
    "Uh oh~",
    "Hehe~",
    "Mmm~",
    "Oh dear~",
    "Tsk tsk~",
    "Ooh la la~",
    "My goodness~",
    "Oh~",
    "Haha~",
  ],
  dry_descriptor: [
    "dry",
    "nice and dry",
    "still dry",
    "completely dry",
    "perfectly dry",
    "fresh and dry",
    "crisp and dry",
    "clean and dry",
    "warm and dry",
    "fluffy",
    "soft and dry",
    "all dry",
    "good and dry",
  ],
  i_think: [
    "I think",
    "I feel",
    "I really think",
    "I honestly think",
    "I believe",
    "I'm thinking",
    "I was thinking",
    "I kinda think",
    "I just think",
  ],
  punctuation: [".", ".", ".", ".", "?", "!", "~", "..."],
  time_expression: [
    "it's time",
    "it's about time",
    "it might be time",
    "maybe it's time",
    "it's probably time",
    "it's definitely time",
    "it could be time",
    "it's getting to be time",
    "it's high time",
  ],
  transition: ["", "for you", "that you", "to have you"],
  afterthought: [
    "#punctuation#",
    " okay?",
    " don't you think?",
    " if you're ready#punctuation#",
    " when you're ready#punctuation#",
    ", sounds good?",
    " alright#punctuation#",
    " if that's okay#punctuation#",
  ],
  change_action: [
    "get a change",
    "have a change",
    "try a change",
    "get changed",
    "have a little change",
    "get a fresh change",
    "get cleaned up",
    "have a fresh one",
    "get a new one",
    "get that taken care of",
  ],
  puddle_observation: [
    "someone made a puddle",
    "somebody had a little accident on the floor",
    "looks like someone missed their diaper",
    "this one made a puddle under them",
    "somebody leaked through",
    "someone's diaper couldn't hold it all",
    "looks like the floor got a surprise",
    "somebody had a little oopsie on the floor",
    "someone's got a leaky diaper",
  ],
  puddle_descriptor: [
    "little puddle",
    "wet spot",
    "puddle",
    "pool",
    "warm puddle",
    "soggy spot",
    "big puddle",
    "small puddle",
    "yellow puddle",
  ],
  wiping_action: [
    "wiping this up",
    "cleaning this up",
    "getting this cleaned",
    "mopping this up",
    "taking care of this",
    "getting rid of this",
  ],
  puddle_ending: [
    "",
    " huh?",
    " is that right?",
    " sweetie?",
    " baby?",
    " what a messy baby~",
    " and they just sit there~",
    " and they don't even care~",
  ],
  wipe_puddle_origin: [
    "#bold_opener# looks like #puddle_observation##puddle_ending#",
    "#bold_opener# #puddle_observation##puddle_ending#",
    "#bold_opener# someone's got a #puddle_descriptor# down here#puddle_ending#",
    "#bold_opener# #wiping_action# from #observation# sitting in a #puddle_descriptor##puddle_ending#",
    "#bold_opener# #observation# made a #puddle_descriptor# on the floor#puddle_ending#",
    "#bold_opener# well that's a #puddle_descriptor# if I've ever seen one#puddle_ending#",
    "#bold_opener# #wiping_action#, somebody's got a leaky #diaper_noun##puddle_ending#",
    "#bold_opener# guess that #diaper_noun# couldn't hold everything#puddle_ending#",
  ],
  change_intro_origin: [
    "#pet_name.capitalize# #unsure_opener# #i_think# #time_expression# #transition# #change_action##afterthought#",
    "#unsure_opener.capitalize# #pet_name#, #i_think# #time_expression# #transition# #change_action##afterthought#",
    "#pet_name.capitalize#, #i_think# #time_expression# #change_action##afterthought#",
  ],
  tease_messy_diaper_origin: [
    "#bold_opener# #observation# has a #mess_descriptor# #diaper_noun##mess_ending#",
    "#bold_opener# #mess_observation##mess_ending#",
    "#bold_opener# someone's #diaper_noun# is #mess_descriptor##mess_ending#",
    "#bold_opener# #observation# made a #mess_descriptor# #diaper_noun##mess_ending#",
    "#bold_opener# that's one #mess_descriptor# little #pet_name##mess_ending#",

    "#bold_opener# #observation# definitely has a #mess_descriptor# #diaper_noun##mess_ending#",
    "#bold_opener# someone's #diaper_noun# is nice and #mess_descriptor##mess_ending#",
    "#bold_opener# #mess_observation##mess_ending#",
    "#bold_opener# yep, that's a #mess_descriptor# #diaper_noun# alright#mess_ending#",

    "#bold_opener# feeling that #mess_descriptor# #diaper_noun#, #pet_name##mess_ending#",
    "#bold_opener# #observation# seems pretty comfortable with that #mess_descriptor# #diaper_noun##mess_ending#",
    "#bold_opener# looks like #observation# #enjoyment_verb# being all #mess_descriptor##mess_ending#",
    "#bold_opener# what a #mess_descriptor# little bottom #observation# has#mess_ending#",
  ],
  tease_wet_diaper_origin: [
    "#bold_opener# #observation# #enjoyment_verb# it being #wetness_descriptor##taunt_ending#",
    "#bold_opener# #observation# #enjoyment_verb# their #diaper_noun# #wetness_descriptor##taunt_ending#",
    "#bold_opener# looks like #observation# #enjoyment_verb# a #wetness_descriptor# #diaper_noun##taunt_ending#",
    "#bold_opener# feeling that #wetness_descriptor# #diaper_noun#, #observation##taunt_ending#",
    "#bold_opener# #observation# definitely #enjoyment_verb# this#taunt_ending#",
    "#bold_opener# someone's #diaper_noun# is #wetness_descriptor##taunt_ending#",
  ],
  patting_dry_diaper_origin: [
    "#bold_opener# #dry_descriptor# in there#taunt_ending#",
    "#bold_opener# someone's got a #dry_descriptor# #diaper_noun##taunt_ending#",
    "#bold_opener# #observation# is #dry_descriptor##taunt_ending#",
    "#bold_opener# feeling that #dry_descriptor# #diaper_noun#, #pet_name##taunt_ending#",
    "#bold_opener# this one's still got a #dry_descriptor# #diaper_noun#, what a good #pet_name##taunt_ending#",
    "#bold_opener# yep, #dry_descriptor# back here#taunt_ending#",
  ],

  // #region Changing table lift
  lift_verb: ["lifts", "hoists", "picks", "scoops", "gently lifts", "carries", "carefully lifts", "takes"],
  lift_middle: [" #name# up", " #name# up and", " #name# over and", " #name#, carrying them", " #name# and"],
  lift_action: [
    "onto the changing table",
    "and lays them on the changing table",
    "and sets them on the changing table",
    "and places them on the changing table",
    "and settles them onto the changing table",
    "to the changing table",
    "up onto the changing table",
    "and puts them on the changing table",
  ],
  change_lift_up_origin: ["#lift_verb##lift_middle# #lift_action#", "#lift_verb# #lift_middle# #lift_action#"],
  // #endregion

  // #region Remove diaper
  remove_verb: ["tugs", "pulls", "rips", "unfastens", "undoes", "releases", "tears"],
  remove_tabs: ["the tabs of", "the tapes on", "the sticky tabs on", "both sides of"],
  remove_diaper_action: [
    "and slides it out from under #name#",
    "and pulls it away",
    "and removes it",
    "and takes it off",
    "and peels it off",
    "and lifts it away",
  ],
  dispose_action: [
    "wraps it up and tosses it away",
    "folds it up and disposes of it",
    "rolls it up and throws it out",
    "bags it up",
    "bins it",
    "disposes of the soiled diaper",
    "tosses it in the pail",
    "puts it in the bin",
  ],
  change_remove_diaper_origin: [
    "#remove_verb# #remove_tabs# #name#'s diaper #remove_diaper_action#, #dispose_action#",
    "#remove_verb# #remove_tabs# #name#'s diaper and #dispose_action#",
    "#remove_verb# #remove_tabs# #name#'s diaper #remove_diaper_action#",
    "#remove_verb# #name#'s diaper open and #dispose_action#",
  ],
  // #endregion

  // #region Wipe
  wipe_verb: ["wipes", "gently wipes", "carefully wipes", "dabs", "cleans", "tenderly wipes", "softly wipes"],
  wipe_area: [
    "#name#'s private bits",
    "#name#'s bottom",
    "#name#'s front and back",
    "#name#'s nether regions",
    "#name#'s diaper area",
    "#name#'s skin",
    "around #name#'s thighs",
    "#name#'s bottom and thighs",
  ],
  wipe_material: [
    "with a warm wipe",
    "with a fresh wipe",
    "using a soft wipe",
    "with a gentle wipe",
    "with a damp cloth",
    "using a fresh cloth",
  ],
  wipe_extra: [
    "",
    " until clean",
    " thoroughly",
    " making sure every bit is clean",
    ", getting all the mess off",
    " to freshen them up",
    " leaving them nice and clean",
  ],
  change_wipe_origin: [
    "#wipe_verb# #wipe_area##wipe_extra#",
    "#wipe_verb# #wipe_area# #wipe_material##wipe_extra#",
    "#wipe_verb# #name#'s bottom and thighs #wipe_material##wipe_extra#",
    "#wipe_verb# around #name#'s diaper area #wipe_material##wipe_extra#",
  ],
  // #endregion

  // #region slide diaper
  slide_verb: ["slides", "slips", "gently slides", "carefully slips", "smooths", "tucks", "places", "positions"],
  slide_diaper_type: [
    "a new diaper",
    "a fresh diaper",
    "a clean diaper",
    "a dry diaper",
    "a new and dry diaper",
    "a fluffy new diaper",
    "a soft diaper",
    "a fresh clean diaper",
  ],
  slide_position: [
    "under #name#'s bottom",
    "beneath #name#",
    "underneath #name#'s bottom",
    "under #name#'s bum",
    "beneath #name#'s backside",
    "under their bottom",
    "into position under #name#",
  ],
  slide_extra: [
    "",
    " and centers it",
    " and smooths it out",
    " and makes sure it's straight",
    ", lining it up just right",
    " before pulling it up",
  ],
  change_slide_diaper_origin: [
    "#slide_verb# #slide_diaper_type# #slide_position##slide_extra#",
    "#slide_verb# #slide_diaper_type# #slide_position#",
  ],
  // #endregion

  // #region seal
  seal_verb: ["draws", "pulls", "gathers", "brings", "folds", "lifts"],
  seal_front: [
    "the front of the diaper up",
    "the diaper up over #name#",
    "the front up",
    "the diaper closed",
    "the diaper together",
  ],
  seal_tabs: [
    "and fastens the tabs",
    "and secures the tapes",
    "and sticks the tabs",
    "and presses the tapes",
    "and attaches the tabs",
    "and closes the tabs",
  ],
  seal_position: [
    "against #name#'s waist",
    "around #name#'s tummy",
    "snug against #name#'s waist",
    "around their middle",
    "against their belly",
    "securely around #name#",
    "nice and snug around #name#",
  ],
  seal_extra: [
    "",
    ", making sure it's secure",
    ", checking the fit",
    ", adjusting for comfort",
    ", ensuring it's snug but not too tight",
    ", smoothing it all down",
  ],
  change_seal_diaper_origin: [
    "#seal_verb# #seal_front# #seal_tabs# #seal_position##seal_extra#",
    "#seal_verb# #seal_front# #seal_tabs# against #name#'s waist#seal_extra#",
    "#seal_verb# #seal_front# and #seal_tabs# #seal_position##seal_extra#",
  ],
  // #endregion

  // #region change ending
  end_opener: ["Mhm~", "There we go~", "All done~", "Aww~", "See~", "Hmm~", "Ahh~", "Perfect~", "And~"],
  end_statement: [
    "that wasn't so hard",
    "that wasn't so bad",
    "all clean and dry now",
    "good as new",
    "nice and fresh",
    "all done and dusted",
    "back in a clean diaper",
    "fresh and comfy again",
  ],
  end_question: [
    "was it~",
    "was it?",
    "right?",
    "hmm?",
    "see?",
    "was that so bad?",
    "wasn't it?",
    "isn't that better?",
    "feels better doesn't it?",
  ],
  end_extra: ["", " much better", " all better now", " back to normal", " good as new now", " all set", " ready to go"],
  change_end_origin: [
    "#end_opener# #end_statement#, #end_extra.capitalize##punctuation#",
    "#end_opener# #end_statement##end_extra##punctuation#",
    "#end_opener# #end_statement# #end_question#",
  ],
  // #endregion

  little_denial_opener: ["Oh?~", "Aww~", "Mhm~", "Hmm~", "Sure~", "Uh-huh~", "Right~", "Of course~", "Is that so~"],

  // Main response variations
  little_denial_statement: [
    "that's what they all say",
    "that's exactly what a little one would say",
    "that's cute coming from you",
    "I'm sure you are",
    "if you say so",
    "whatever helps you sleep at night",
    "that's adorable",
    "sure you are",
    "and I'm the queen of England",
    "in your dreams, little one",
    "that's rich coming from you",
    "you keep telling yourself that",
  ],

  // Follow-up questions/tags
  little_denial_question: [
    "is it?",
    "really?",
    "are you?",
    "sure about that?",
    "is that right?",
    "you think so?",
    "do you now?",
    "for real?",
  ],
  little_denial_origin: [
    "#little_denial_opener.capitalize#, #little_denial_statement#, #little_denial_question# #pet_name.capitalize##punctuation#",
    "#little_denial_opener.capitalize#,#little_denial_statement# #pet_name##punctuation#",
    "#little_denial_opener.capitalize#, #little_denial_statement# #little_denial_question# #pet_name.capitalize##punctuation#",
    "#little_denial_statement.capitalize#, #little_denial_question# #pet_name.capitalize##punctuation#",
    "#little_denial_opener.capitalize#, #little_denial_question# #little_denial_statement.capitalize# #pet_name##punctuation#",
  ],
});
grammar.addModifiers(tracery.baseEngModifiers);
